---
title: "data405a1"
output: pdf_document
date: "2025-9-25"
---


# Data 405 Assignment 1

## Q1 code:

```{r}

unirand <- function(n, s) {
    # moduluo & multiplier variables
    m <- 30307
    a <- 172

    x <- integer(n)   # raw sequence
    u <- numeric(n)   # normalized seq

    x[1] <- (a * s) %% m
    u[1] <- x[1] / m

    if (n > 1) {
        for (i in 2:n) {
            x[i] <- (a * x[i-1]) %% m
            u[i] <- x[i] / m
        }
    }
    return(u)
}

# s is for seed, n is for number, m is for modulo, a is for multiplier, x is for raw sequence, u is for normalized sequence

```

```{r}

# 10 uniforms using unirand1 with seed = 13
unirand(10, 13)

```

## Q1 discussion:

The maximal cycle length of a multiplicative congruential generator with moduluo m
requires that the 'a' variable be a primitive root modulo m. Since 172 is NOT a primitive root of modulo 30307,
this generator does NOT achieve maximal cycle length (which would be m-1 = 30306)

## Q2 code:

```{r}

unirand2 <- function(n, s) {
    m <- 30323
    a <- 170

    x <- integer(n)
    u <- numeric(n)

    x[1] <- (a * s) %% m
    u[1] <- x[1] / m

    if (n > 1) {
        for (i in 2:n) {
            x[i] <- (a * x[i-1]) %% m
            u[i] <- x[i] / m
        }
    }
    return(u)
}

# s is for seed, n is for number, m is for modulo, a is for multiplier, x is for raw sequence, u is for normalized sequence

```

```{r}

# 10 uniforms using unirand1 with seed = 13
unirand2(10, 42)

```

